   steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      # Use a robust command to find and change permissions, just in case the path is non-standard
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
        

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/project-4d5df146-2d65-4df5-8443-ede7ad9a790b:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/project-4d5df146-2d65-4df5-8443-ede7ad9a790b:latest

  deploy-and-health-check:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/project-4d5df146-2d65-4df5-8443-ede7ad9a790b:latest

      - name: Run Docker container
        run: |
          docker run -d --name my-app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/project-4d5df146-2d65-4df5-8443-ede7ad9a790b:latest
          sleep 30

      - name: Health Check
        run: curl --retry 5 --retry-delay 5 http://localhost:8080/ || exit 1

      - name: Clean up Docker container
        if: always()
        run: |
          docker stop my-app || true
          docker rm my-app || true
